server:
  port: 9090

spring:
  application:
    name: up

#ToDO 邮箱配置
  mail:
    host: smtp.qq.com
    port: 25
    username: 2953126974@qq.com
    password: ju187369
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 187369
    url: jdbc:mysql://localhost:3306/up?useUnicode=true&characterEncoding=UTF-8
    username: root




